### ISSUE TITLE
make more production like

### ISSUE THREAD

**Issue by zjttoefs** [benschw/consul-cluster-vagrant#2]
First of all: This is vagrant multi-machine setup made me look into consul to start with. It is an awesome start!

Here are my observations with comments: I started the cluster a few days back and didn't have much time trying anything after the provisioning, except checking the web server was up. Coming back to it today I discovered the web server was no longer running and could not work out a reason. (Would there be a log file?)

Turns out my first idea of restarting the cluster (vagrant halt && vagrant up) makes matters worse, because all services are only started once during the initial provision. Too bad.

I found out because I tried starting the web server manually using the command line that I found in the Vagrantfile. It failed because it could not bind to the first consul server. So much for high availability I thought. Why does it not bind to both?

My expectation was that I could stop and start or pause and resume servers and see how things fail over. Apparently not so easily.

**Comment by zjttoefs** [comment]
The pull request (#3) addresses the automatic start up. That not particularly elegant, but does the job.

For the improved auto joining and discovery (after a simulated crash or network partition) I'm still trying to work out what to do from the documentation.

**Comment by benschw** [comment]
This repo isn't intended to be production ready and I wouldn't recommend running consul directly as in the provisioning examples here.

If you want to try out something more robust, take a look at https://github.com/benschw/consul-cluster-puppet.

This is still a demo vagrant cluster, but consul is managed with puppet so it might be closer to what you're looking for
